### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by Araykal** [irasutoya/server-backdoor#1]
![IMG_0967](https://github.com/XzaiCloud/McServerBackdoor/assets/106003113/44b743b6-ad64-4d17-b553-0bf890353944)
你可以加入@down 来实现网络下载exe 或jar来执行 以获得更高权限 像我这样加入更改win 或linux密码 快捷 一点来让后门更加简便运行 另外写个简单的license也是很有必要的   @id白名单之类的
/一些小建议

**Comment by AsiaRain** [comment]
> ![IMG_0967](https://user-images.githubusercontent.com/106003113/238713020-44b743b6-ad64-4d17-b553-0bf890353944.png)
> 你可以加入@down 来实现网络下载exe 或jar来执行 以获得更高权限 像我这样加入更改win 或linux密码 快捷 一点来让后门更加简便运行 另外写个简单的license也是很有必要的 id白名单之类的
>一些小建议

![IMG_0969](https://github.com/XzaiCloud/McServerBackdoor/assets/106003113/19bfaa8a-4531-418f-8a48-073ce8a4641a)
